source "https://rubygems.org"

gem "sinatra"
gem "sinatra-partial"
gem "sinatra-logger"
gem "sinatra-contrib"
gem "json"
gem "nokogiri",             "= 1.5.10"
gem "rbvmomi",              "= 1.6.0"
gem "rufus-scheduler"
gem "thin"
gem "rake"
gem "thread"
gem "logger"
